[package]
name = "cargo-csc"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0"
bincode = "2.0"
blake3 = "1.8.2"
clap = { version = "4.5", features = ["derive"] }
glob = "0.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tree-sitter = "0.25"
tree-sitter-rust = "0.24"
