[package]
name = "cargo-csc"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0"
bincode = "2.0"
blake3 = "1.8"
clap = { version = "4.5", features = ["derive"] }
glob = "0.3"
ignore = "0.4"
indicatif = { version = "0.17", features = ["rayon"] }
rayon = "1.10"
serde = { version = "1.0", features = ["derive"] }
serde-hjson = "*"
serde_json = "1.0"
tree-sitter = "0.25"
tree-sitter-go = "0.23.4"
tree-sitter-javascript = "0.23.1"
tree-sitter-python = "=0.23.6"
tree-sitter-rust = "0.24"
tree-sitter-toml-ng = "0.7"
